[project]
name = "sigconverter-frontend"
version = "1.0.0"
description = "frontend for the sigconverter projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["flask>=3.0.3", "requests>=2.32.3"]
authors = [{ name = "Magic Sword", email = "info@magicsword.io" }]
