# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Frontend Packages Test

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  pip-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Test uv package installation
        run: uv venv && uv pip sync pyproject.toml
        working-directory: frontend
